/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://maven.pkg.github.com/APDevTeam/Movecraft")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }

    maven {
        url = uri("https://hub.spigotmc.org/nexus/content/repositories/snapshots/")
    }

    maven {
        url = uri("https://oss.sonatype.org/content/repositories/snapshots")
    }

    maven {
        url = uri("https://maven.enginehub.org/repo/")
    }

    maven {
        url = uri("https://jitpack.io")
    }
}

dependencies {
    api(libs.org.jetbrains.annotations.java5)
    compileOnly(libs.org.spigotmc.spigot.api)
    compileOnly(libs.org.spigotmc.spigot)
    compileOnly(libs.net.countercraft.movecraft)
    compileOnly(libs.com.sk89q.worldguard.worldguard.bukkit)
    compileOnly(libs.com.github.milkbowl.vaultapi)
    system(libs.net.countercraft.movecraft.worldguard.movecraft.worldguard)
}

group = "snowleapord.github.com"
version = "3.0.0_beta-2"
description = "APTurrets"
java.sourceCompatibility = JavaVersion.VERSION_17

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
