main: com.snowleopard1863.APTurrets.TurretsMain
version: ${project.version}
name: APTurrets
api-version: 1.18
authors: [TylerS1066, Snowleopard1863, cccm5, MrUniverse_]
depend: [Movecraft, Movecraft-WorldGuard, Vault]

permissions:
  ap-turrets.use:
    default: op
  ap-turrets.regionoverride:
    default: op
  ap-turrets.place:
    default: op
