main: com.snowleopard1863.APTurrets.TurretsMain
version: 2.3.5
name: APTurrets
authors: [Foxtrot2400, Snowleopard1863, TylerS1066, cccm5, MrUniverse_]

depend: [Movecraft, WorldGuard, Vault, WorldEdit]
