name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache Maven packages
      id: cache
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2
        restore-keys: ${{ runner.os }}-m2

# Run Spigot BuildTools for NMS if required
    - name: Setup BuildTools
      run: mkdir BuildTools && wget -O BuildTools/BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar

    - name: Check 1.10.2
      id: frostburn
      run: test -f ~/.m2/repository/org/bukkit/craftbukkit/1.10.2-R0.1-SNAPSHOT/craftbukkit-1.10.2-R0.1-SNAPSHOT.jar && echo "::set-output name=sucess::true" || echo "::set-output name=sucess::false"
    - name: Build 1.10.2
      if: steps.frostburn.outputs.sucess != 'true'
      run: cd BuildTools && java -jar BuildTools.jar --rev 1.10.2

    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Stage jar
      run: mkdir staging && cp target/APTurrets*.jar staging
    - name: Rename jar
      run: mv staging/APTurrets*.jar staging/APTurrets_$GITHUB_SHA.jar
    - name: Upload jar
      uses: actions/upload-artifact@v2
      with:
        name: APTurrets_Dev-Build
        path: staging/APTurrets_*.jar
